### ISSUE TITLE
x86_64 1.2 install silently fails when launched by taskbar icon

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#161] opened 2023-03-04 00:54 UTC
**Steps to Reproduce**
1. Downloaded 1.2 (either version) used debian Software Install to implement
2. clicking on QPrompt icon in Audio/Video section of taskbar results in silent app abort.
3. Repeating same steps with 1.1.5 executes as expected.

**Device information**
 - Operating System: Debian x86_64 Bullseye, latest updates

**Comment by Cuperino** [comment] 2023-03-04 01:48
What output do you get when launching 1.2 from the terminal by typing `qprompt`?

**Comment by videosmith** [comment] 2023-03-04 02:40
![screen1](https://user-images.githubusercontent.com/88691671/222871668-f031a2b6-a1b8-4e82-a03b-d10b7a5e7485.png)

**Comment by Cuperino** [comment] 2023-03-04 02:51
I didn't release a 1.2.0-01 AppImage because it experiences a similar startup crash. I suspected that it was caused by 1.2's inclusion of Qt's QNetworkRequest library. If your system lacks this library that would explain why it fails to start.

Running qprompt from the terminal should tell you if there are any libraries that are missing, but what I see here is that the app actually reaches a point that can only be reached when all libraries have successfully loaded, which is not what I was expecting.

- QHotkey fails to bind the key shortcut because the resource wasn't clear by QPrompt when it first crashed. Making a note for when I work on global hotkeys.
- The cyclic dependency sounds like the most likely culprit, but that sounds like an issue with Debian's packages that would prevent all versions of QPrompt from running.

**Comment by videosmith** [comment] 2023-03-04 02:56
However 1.1.5 runs as expected, albeit with the possible config snag...

**Comment by Cuperino** [comment] 2023-03-04 03:00
What you're experiencing might be the same problem that prevented me from running the AppImage on my computer. The only difference is that the AppImage didn't give me any terminal output. Now we have something to go by.

**Comment by Cuperino** [comment] 2023-03-04 03:04
What output do you get when you run 1.1.5 from the terminal? I'd like to compare the two if possible.

**Comment by Cuperino** [comment] 2023-03-04 03:05
Also, does 1.2 run fine on the Raspberry Pi?

**Comment by videosmith** [comment] 2023-03-04 03:17
> What output do you get when you run 1.1.5 from the terminal? I'd like to compare the two if possible.
![screen1](https://user-images.githubusercontent.com/88691671/222873189-38453bf0-a5c3-46c2-92bc-3c91322d9fdb.png)

**Comment by videosmith** [comment] 2023-03-04 03:18
> Also, does 1.2 run fine on the Raspberry Pi?

Only briefly tested, however so far executes as expected.

**Comment by Cuperino** [comment] 2023-04-02 16:23
Forgot to close this issue. The startup crash was due to a missing implementation detail in the opening of remote files. The issue was fixed in v1.2.0-03.

**Closed by Cuperino** 2023-04-02 16:23 UTC
Labels: bug, hotkeys
