### ISSUE TITLE
Next marker button/hotkey does not cycle through entire Welcome script

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#147] opened 2023-01-18 22:33 UTC
**Bug Description**
Selecting Next Marker in any method only advances through the first two bookmarks in the Welcome script (selecting them in the Bookmark list works as expected).  Previous Marker moves back through all markers correctly.

In other scripts, works correctly.

**Expected behavior**
Next/Previous functions should be identical in operation.

**Screenshots** (optional)
![info](https://user-images.githubusercontent.com/88691671/213309630-8cb10856-47b6-44e8-91e3-8bde6869ec0c.png)

**Device information**
 - QPrompt Version: qprompt-v1.1.3-aa79ad5-linux-gcc-x86_64.AppImage
 - Operating System; Debian 11, latest updates

**Comment by Cuperino** [comment] 2023-01-19 00:53
This sounds like bug #85, which I couldn't get rid of for this release.

The bug has been around for a while, but it can be difficult to catch because it happens under very specific circumstances, depending factors like window size.and text placement. What seems to be happening is that the search looks for the next marker but finds the current marker instead because of a computation error that happens when the marker starts in one line but ends on another.

I'm closing this issue as a duplicate of #85. If you have a reason to think it may be something else, please let me know.

**Closed by Cuperino** 2023-01-19 00:53 UTC
Labels: duplicate

**Comment by videosmith** [comment] 2023-01-19 01:19
Not an issue if it only manifests on the Welcome script. As I stated, another I created worked correctly. Was just giving an update.
    On Wednesday, January 18, 2023, 07:53:31 PM EST, Javier O. Cordero Pérez ***@***.***> wrote:  
 
 


This sounds like bug #85, which I couldn't get rid of for this release.

The bug has been around for a while, but it can be difficult to catch because it happens under very specific circumstances, depending factors like window size.and text placement. What seems to be happening is that the search looks for the next marker but finds the current marker instead because of a computation error that happens when the marker starts in one line but ends on another.

I'm closing this issue as a duplicate of #85. If you have a reason to think it may be something else, please let me know.

**Comment by Cuperino** [comment] 2023-01-19 01:27
Thanks. This is something that could happen in any script, but the chances of it happening are very very low.

You can reduce those chances to absolute 0 by creating markers that are never placed at the end of a line.
