### ISSUE TITLE
Qprompt beta 1.1.0 install issue

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#106] opened 2022-08-04 00:13 UTC
**Bug Description**
App will not run

**Steps to Reproduce**
1. Used Add/Remove software to uninstall 1.0 version
2. Right clicked on 'qprompt-main-0fbee21-linux-aarch64-gcc.deb' package.   Select 'Package Install' from contextual menu
3. After install completes, Clicked on Qprompt in the Sound & Video portion of the main menu.
4. Brief drive activity with hourglass cursor then no change.
5. reboot/restart, no change

**Expected behavior**
Program should launch like the 1.0 version does successfully.

**Device information**
 - QPrompt Version: see above
 - Operating System: RPi 400 Bullseye 64, latest updates, same desktop environment as before

**Comment by Cuperino** [comment] 2022-08-04 01:01
It's missing KCrash, a new dependency. KCrash is a library that handles crashes graciously and helps users collect crash data. My mistake was I compiled QPrompt to use KCrash but forgot to update the Debian package to auto install that dependency. The issue is already fixed in the [second release candidate](https://github.com/Cuperino/QPrompt/releases/tag/v1.1.0-rc-2).

To use the first release candidate, install KCrash by running:
`sudo apt install libkf5crash5`

**Closed by Cuperino** 2022-08-04 01:01 UTC
Labels: distribution
