### ISSUE TITLE
Scrolling issue with Top cursor Reading Region selected

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#178] opened 2023-04-30 17:16 UTC
**Bug Description**
Text will not animate under specific order of  operations.

**Steps to Reproduce**
1. Launch QPrompt
2. While in windowed (un-maximized) mode, with left-pointer only selected for Reading Region indicator, set to Top
3. Using Ctrl-F11, maximize window
4.  Using F8, enter prompt mode
5.  No default scroll speed, no reaction to mouse on screen
6.  Must use Ctrl-F11 to un-maximize window, then animation begins and mouse control returns
7.  Also exhibits incorrect window display behavior when prompting in windowed mode.

**Expected behavior**
Should perform the same as when Reading Region set to Middle

**Screenshots** (optional)
![20230430_130952](https://user-images.githubusercontent.com/88691671/235366812-02328f08-d367-4bf7-bba1-802303cf6f72.jpg)
![20230430_131134](https://user-images.githubusercontent.com/88691671/235366813-65c295ef-5ba6-4d07-b30d-ae8de006ac4b.jpg)

**Device information**
 - QPrompt Version: 1.2, rev 4
 - Operating System: Ubuntu 22.04, latest updates
 - RPi 4B, 400

**Comment by Cuperino** [comment] 2023-04-30 18:41
I followed the steps with a couple of changes due to differences on my system, that shouldn't result in a different outcome. Following the steps in order resulted in the expected behaviors. The differences were:

- Used Ctrl+Shift+F to enter FullScreen
- Used F5 to toggle the prompter because F8 is occupied by my desktop environment for some action
- I ran KDE Plasma instead of Gnome

Please check that there's no collision with the shortcut used to toggle QPrompt in your system. You can check this by pressing the shortcut normally and validating that it toggles the prompter's state, or by changing the toggle shortcut to some other key and validating that it works.

Also, possibly more relevant to replicate this issue, please indicate:
-  How are the `Countdown` settings configured in your QPrompt instance.

**Comment by videosmith** [comment] 2023-04-30 22:30
Also happens with mouse interaction:
1. Launch QPrompt in un-maximized windowed mode
2. Click Top in Reading Region (left pointer only)
3. Click maximize icon in window frame
4. Click Fullscreen
5. Click Start Prompter -may freeze at this step
6. Click Blue disc start prompting icon at bottom of app
7. Only way out is to use shortcut keys to un-maximize window.
8. Also window decorations incorrect if prompting in unmaximized mode occasionally.

**Comment by videosmith** [comment] 2023-06-02 23:07
Countdown option left un-checked

**Comment by Cuperino** [comment] 2023-06-03 00:40
I'm still unable to replicate the first issue where the prompter won't scroll...

As for the window decorations and top toolbar disappearing, that is actually done on purpose such that the prompter window can reach the very top of the screen while prompting (or outside of edit mode). This is primarily meant for people who record using a webcam or camera above their screens, and have QPrompt in windowed mode to use other applications at the same time.

When the reading region is set to the bottom, the editor toolbar auto hides instead.

**Comment by Cuperino** [comment] 2023-10-02 01:23
Closing as unable to replicate. Feel free to re-open if you continue to experience this issue.

**Closed by Cuperino** 2023-10-02 01:23 UTC
Labels: more info needed, unable-to-replicate
