### ISSUE TITLE
NDI enabled

### ISSUE THREAD

**Issue by IVEN2022** [Cuperino/QPrompt#142] opened 2022-12-30 17:30 UTC
I dont know is the QP structure can have NDI technology enabled  https://www.ndi.tv/sdk/

Also Secondary screen possibility

**Comment by Cuperino** [comment] 2022-12-30 17:59
It can, but NewTek's NDI license requires me to impose certain use restrictions that conflict with the General Public License's requirements. This means that, even though a GPL version of QPrompt that supports NDI can exist, its builds cannot ship with the feature enabled and you would have to build QPrompt yourself to have NDI work. Due to this, any future versions of QPrompt that ship with NDI support enabled will be paid for and ship under a proprietary license.

It could theoretically be free of charge and proprietary, but this makes no economic sense because I'd be required to pay for other libraries QPrompt uses in order to distribute them in the proprietary binaries, and I'd have no way to recoup that cost.

With regards to the secondary screen, QPrompt allows duplicating the prompter's screen already but the editor and prompter are one and the same. I'm working on a version of QPrompt that decouples the editor from the prompter, but it's still in its infancy. When it releases, it will also be paid for to establish the precedent for when NDI support is added.

Closing issue because it's a duplicate of #41.

**Closed by Cuperino** 2022-12-30 17:59 UTC
Labels: duplicate

**Comment by Cuperino** [comment] 2022-12-30 18:36
To be clear about this. QPrompt and its future versions are and will always be GPL licensed. Builds from the paid version would be distributed under a slightly different name, and regular QPrompt would continue to be developed, sharing features between the two versions.
