### ISSUE TITLE
Save files with anchors

### ISSUE THREAD

**Issue by avlinkus** [Cuperino/QPrompt#64] opened 2022-02-16 07:05 UTC
**Bug Description**
Not able to save the xhtml files with anchors and shortcuts but works when well edited in the file. See file attached.
...

**Steps to Reproduce**

1. ...
2. ...

**Expected behavior**

...

**Detailed description of display configuration** (if applicable)
[Markers.zip](https://github.com/Cuperino/QPrompt/files/8077525/Markers.zip)

...

**Screenshots** (if applicable)

...

**Device information**
 - Operating System: Windows
 - QPrompt Version: qprompt-v1.0-2c9752c-v1.0-windows-msvc2019_64-cl

**Additional context**

...

**Comment by Cuperino** [comment] 2022-02-16 07:53
This is a duplicate of issue #58, but thanks for reporting.

**Closed by Cuperino** 2022-02-16 07:53 UTC
Labels: duplicate
