### ISSUE TITLE
Text decorations not applying

### ISSUE THREAD

**Issue by videosmith** [Cuperino/QPrompt#93] opened 2022-06-27 22:42 UTC
**Bug Description**
Unable to apply text decorations (size, underline, etc.) through contextual menu

**Steps to Reproduce**
1. Load the default script
2. Select some text
3. Right-click on the selected text and select Font...
4.  Adjust size or underline.

**Expected behavior**
Font decorations should apply to selected text.

**Detailed description of display configuration** (if applicable)
qprompt-v1.0-2c9752c-v1.0-linux-64-gcc.AppImage

![specs](https://user-images.githubusercontent.com/88691671/176048144-02ca692e-8c59-4a46-98ad-160dd41543bc.jpg)

**Comment by Cuperino** [comment] 2022-06-28 06:23
This is a duplicate of issue #25.

The font dialog is shown is provided by the OS or the desktop environment in the case of Gnome, Plasma, Windows, and macOS. I can only choose what to do with the information received from the dialogs, but I cannot do much about the dialogs themselves. Changing font sizes from this dialog has the potential of breaking how the font slider works, which is why that setting is ignored.

What I plan on doing is create my own dialog and replace the native dialogs with it. This is a low priority item that involves a considerable amount of work. The ideal solution is improve Qt's font dialog code upstream, so that it allows for more granularity on which fields are to be shown. To effectively do that, both KDE Frameworks and QPrompt first need to complete the transition to Qt version 6.

**Closed by Cuperino** 2022-06-28 06:23 UTC

**Comment by videosmith** [comment] 2022-07-03 02:27
The font slider works great.... however it affects all the text simultaneously.  Occasionally a client would like specific text at a different size (emphasis, readability etc.), so that ability would be nice to have.

**Comment by Cuperino** [comment] 2022-07-03 03:45
> Occasionally a client would like specific text at a different size (emphasis, readability etc.), so that ability would be nice to have.

The issue with having text of different sizes is that it can screw with QPrompt's ability to estimate the presenters' desired reading speeds. This is a feature that I've been planning since the start, but is still awaiting for groundwork to be completed before it's actually implemented. Discussion about that can be found at #19.

**Comment by Cuperino** [comment] 2022-07-03 03:53
I also thought about giving the option anyway and compensate for it using math, but the other problem that we have is that Qt's subset of HTML and CSS used in editor is much more limited than that of a web browser, which means the relative `em` unit used to achieve this in Imaginary Teleprompter is not available to us, and there's no easy way to allow assigning text size without breaking font scaling for those lines...
